"""
Django settings for neuromeet project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import ipaddress
import socket
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env (if present)
ENV_PATH = BASE_DIR / '.env'

def _load_env_file(path: Path) -> None:
    if not path.exists():
        return
    for raw_line in path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#'):
            continue
        if '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value

_load_env_file(ENV_PATH)


def _env_bool(name: str, default: bool = False) -> bool:
    raw_value = os.getenv(name)
    if raw_value is None:
        return default
    return raw_value.strip().lower() in {'1', 'true', 'yes', 'on'}


def _env_list(name: str, default: str = '') -> list[str]:
    raw_value = os.getenv(name, default)
    return [item.strip() for item in raw_value.split(',') if item.strip()]


def _append_unique(items: list[str], value: str) -> None:
    if value and value not in items:
        items.append(value)


def _database_config() -> dict[str, object]:
    database_url = os.getenv('DATABASE_URL', '').strip()

    if not database_url:
        return {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }

    parsed = urlparse(database_url)
    scheme = parsed.scheme.lower()

    if scheme in {'postgres', 'postgresql', 'pgsql'}:
        config: dict[str, object] = {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': unquote(parsed.path.lstrip('/')) or 'postgres',
        }

        if parsed.username:
            config['USER'] = unquote(parsed.username)
        if parsed.password:
            config['PASSWORD'] = unquote(parsed.password)
        if parsed.hostname:
            config['HOST'] = parsed.hostname
        if parsed.port:
            config['PORT'] = parsed.port

        options = {
            key: values[-1]
            for key, values in parse_qs(parsed.query).items()
            if values
        }
        if options:
            config['OPTIONS'] = options

        return config

    if scheme == 'sqlite':
        raw_path = unquote(parsed.path or '').lstrip('/')
        db_path = Path(raw_path) if raw_path else BASE_DIR / 'db.sqlite3'
        if not db_path.is_absolute():
            db_path = BASE_DIR / db_path
        return {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': db_path,
        }

    raise ValueError(f'Unsupported DATABASE_URL scheme: {scheme}')


def _local_ipv4_hosts() -> list[str]:
    hosts: set[str] = set()
    addresses: set[str] = set()

    try:
        for info in socket.getaddrinfo(socket.gethostname(), None, socket.AF_INET):
            addresses.add(info[4][0])
    except OSError:
        pass

    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sock:
            sock.connect(('8.8.8.8', 80))
            addresses.add(sock.getsockname()[0])
    except OSError:
        pass

    for address in addresses:
        try:
            ip = ipaddress.ip_address(address)
        except ValueError:
            continue

        if ip.version != 4 or ip.is_loopback or ip.is_link_local:
            continue
        hosts.add(address)

    return sorted(hosts)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-lu)vc9(3oeu=cl@nv+g*o^24&te6!hesi$sut9h3($qa48#@oi')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DEBUG', True)
ALLOW_ALL_HOSTS_IN_DEBUG = _env_bool('ALLOW_ALL_HOSTS_IN_DEBUG', DEBUG)
APP_BASE_URL = os.getenv('APP_BASE_URL', '').strip().rstrip('/')

ALLOWED_HOSTS = _env_list('ALLOWED_HOSTS', '127.0.0.1,localhost')

if DEBUG and ALLOW_ALL_HOSTS_IN_DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    for host in _local_ipv4_hosts():
        if host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(host)

if APP_BASE_URL:
    parsed_base_url = urlparse(APP_BASE_URL)
    if parsed_base_url.hostname:
        _append_unique(ALLOWED_HOSTS, parsed_base_url.hostname)


# Application definition
INSTALLED_APPS = [

'daphne',
'channels',

'meetings',
'ai_assistant',

'django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',

 'social_django',

]

ASGI_APPLICATION = "neuromeet.asgi.application"

REDIS_URL = os.getenv('REDIS_URL', '').strip()

if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'neuromeet.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # <-- yahan templates folder path specify karo
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.github.GithubOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

WSGI_APPLICATION = 'neuromeet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': _database_config()
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = Path(os.getenv('STATIC_ROOT', str(BASE_DIR / 'staticfiles')))

MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.getenv('MEDIA_ROOT', str(BASE_DIR / 'media')))
SERVE_MEDIA = _env_bool('SERVE_MEDIA', DEBUG)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'app_home'
LOGOUT_REDIRECT_URL = 'login'

CSRF_TRUSTED_ORIGINS = _env_list('CSRF_TRUSTED_ORIGINS')
if APP_BASE_URL and urlparse(APP_BASE_URL).scheme in {'http', 'https'}:
    _append_unique(CSRF_TRUSTED_ORIGINS, APP_BASE_URL)

ENABLE_HTTPS = _env_bool('ENABLE_HTTPS', False)
ALLOW_EMBEDDED_PREVIEW = _env_bool('ALLOW_EMBEDDED_PREVIEW', DEBUG)
USE_WHITENOISE = _env_bool('USE_WHITENOISE', False)

if USE_WHITENOISE:
    try:
        import whitenoise  # noqa: F401
    except ImportError as exc:
        if DEBUG:
            USE_WHITENOISE = False
        else:
            raise RuntimeError(
                "WhiteNoise is required when USE_WHITENOISE is enabled in production."
            ) from exc

if USE_WHITENOISE:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
SECURE_SSL_REDIRECT = ENABLE_HTTPS
SESSION_COOKIE_SECURE = ENABLE_HTTPS
CSRF_COOKIE_SECURE = ENABLE_HTTPS
SECURE_HSTS_SECONDS = 31536000 if ENABLE_HTTPS else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = ENABLE_HTTPS
SECURE_HSTS_PRELOAD = ENABLE_HTTPS
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
X_FRAME_OPTIONS = 'DENY'

if ALLOW_EMBEDDED_PREVIEW:
    MIDDLEWARE = [
        middleware
        for middleware in MIDDLEWARE
        if middleware != 'django.middleware.clickjacking.XFrameOptionsMiddleware'
    ]

if USE_WHITENOISE:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

# Social Auth (set these in your environment)
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY', '')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET', '')
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ['email', 'profile']

SOCIAL_AUTH_GITHUB_KEY = os.getenv('SOCIAL_AUTH_GITHUB_KEY', '')
SOCIAL_AUTH_GITHUB_SECRET = os.getenv('SOCIAL_AUTH_GITHUB_SECRET', '')
SOCIAL_AUTH_GITHUB_SCOPE = ['user:email']

SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL = True
