# Generated by Django 5.2.12 on 2026-03-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auto_transcription',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='default_mic',
            field=models.CharField(blank=True, default='default', max_length=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='default_speaker',
            field=models.CharField(blank=True, default='default', max_length=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='noise_cancellation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='product_updates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='weekly_summary',
            field=models.BooleanField(default=True),
        ),
    ]
